### ISSUE TITLE
flake8-check-action fails with a pull-request from a forked repository

### ISSUE THREAD

**Issue by taylorbell57** [tonybajan/flake8-check-action#8]
I really appreciate your flake8 check action, and just started using it on an open-source project that I am working on (https://github.com/kevin218/Eureka). So far it works great when working on branches of the main repository, but I just encountered a bug where a pull-request was opened from a forked repository, and the flake8 test fails to run giving me a 403 Client Error. The full traceback is copied below:

```
Run tonybajan/flake8-check-action@v1.2.0
  with:
    select: E1,E2,E3,E4,E5,E7,W6,F
    ignore: W504,W503,E704,E226,E722
    maxlinelength: 100
    repotoken: ***
/usr/bin/docker run --name f15549f0c5fb9a86c49bd86a8791c81183964_310d74 --label 6f1554 --workdir /github/workspace --rm -e INPUT_SELECT -e INPUT_IGNORE -e INPUT_MAXLINELENGTH -e INPUT_REPOTOKEN -e INPUT_PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Eureka/Eureka":"/github/workspace" 6f1554:9f0c5fb9a86c49bd86a8791c81183964
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/flake8_check_action/__main__.py", line 60, in <module>
    exit_code = run_check()
  File "/usr/local/lib/python3.9/site-packages/flake8_check_action/__main__.py", line 27, in run_check
    check_run = GitHubCheckRun(github_token, repo, sha, workspace=workspace, path=path)
  File "/usr/local/lib/python3.9/site-packages/flake8_check_action/github.py", line 45, in __init__
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/kevin218/Eureka/check-runs
```

Any guidance on if/how this issue can be resolved would be much appreciated! If it is helpful, the current .yml file is located at https://github.com/kevin218/Eureka/blob/main/.github/workflows/flake8_linting.yml

**Comment by tonybajan** [comment]
It looks like forked repos are [restricted](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) to getting read permissions on the checks API only. I can fix this so that the action will still complete, but the rich PR annotations will unfortunately not be available.

**Comment by taylorbell57** [comment]
Ah okay, well that would definitely be an improvement - thanks for the very rapid response!
